name: Simple
options:
  bundleIdPrefix: com.finclip.chatkit
  deploymentTarget:
    iOS: "16.0"

schemes:
  Simple:
    build:
      targets:
        Simple: all
    run:
      config: Debug

packages:
  FinClipChatKit:
    url: https://github.com/Geeksfino/finclip-chatkit.git
    from: 0.7.4
  finclip-neuron:
    url: https://github.com/Geeksfino/finclip-neuron.git
    branch: main-swift6_0

targets:
  Simple:
    type: application
    platform: iOS
    sources:
      - path: App/App
      - path: App/Extensions
      - path: App/ViewControllers
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.finclip.chatkit.simple
      PRODUCT_NAME: Simple
      INFOPLIST_KEY_CFBundleDisplayName: Simple
      INFOPLIST_FILE: App/App/Info.plist
      ENABLE_BITCODE: NO
    dependencies:
      - product: FinClipChatKit
        package: FinClipChatKit
      - product: NeuronKit
        package: finclip-neuron
      - product: SandboxSDK
        package: finclip-neuron  
      - product: convstorelib
        package: finclip-neuron
      - product: ConvoUI
        package: finclip-neuron  

