name: AI-Bank-OC

options:
  bundleIdPrefix: com.finclip
  deploymentTarget:
    iOS: "16.0"
  createIntermediateGroups: true

packages:
  finclip-chatkit:
    url: https://github.com/Geeksfino/finclip-chatkit.git
    from: 0.2.1

targets:
  AI-Bank-OC:
    type: application
    platform: iOS
    
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.finclip.ai-bank-oc
      DEVELOPMENT_TEAM: ""
      CODE_SIGN_STYLE: Automatic
      SWIFT_VERSION: "5.9"
      CLANG_ENABLE_OBJC_ARC: YES
      ENABLE_BITCODE: NO
      FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks @loader_path/Frameworks/FinClipChatKit.framework/Frameworks
      SWIFT_INCLUDE_PATHS[sdk=iphoneos*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      SWIFT_INCLUDE_PATHS[sdk=iphonesimulator*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
        
    sources:
      - App
      
    dependencies:
      - package: finclip-chatkit
        product: ChatKit
    
    postbuildScripts:
      - name: Sign Nested ChatKit Frameworks
        shell: /bin/sh
        script: |
          FRAMEWORK_DIR="${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/FinClipChatKit.framework/Frameworks"
          if [ -d "${FRAMEWORK_DIR}" ]; then
            find "${FRAMEWORK_DIR}" -type d -name "*.framework" -print0 | while IFS= read -r -d '' FRAME; do
              /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --preserve-metadata=identifier,entitlements "${FRAME}" || exit 1
            done
          fi
        
    info:
      path: App/App/Info.plist
      properties:
        CFBundleDisplayName: AI-Bank-OC
        UILaunchScreen: {}


