name: SimpleObjC
options:
  bundleIdPrefix: com.finclip.chatkit
  deploymentTarget:
    iOS: "16.0"

schemes:
  SimpleObjC:
    build:
      targets:
        SimpleObjC: all
    run:
      config: Debug

packages:
  ChatKit:
    url: https://github.com/Geeksfino/finclip-chatkit.git
    from: 0.6.1

targets:
  SimpleObjC:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - "**/*.swift"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.finclip.chatkit.simpleobjc
      PRODUCT_NAME: SimpleObjC
      INFOPLIST_KEY_CFBundleDisplayName: SimpleObjC
      INFOPLIST_FILE: App/Info.plist
      ENABLE_BITCODE: NO
      FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks @loader_path/Frameworks/FinClipChatKit.framework/Frameworks
      SWIFT_INCLUDE_PATHS[sdk=iphoneos*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      SWIFT_INCLUDE_PATHS[sdk=iphonesimulator*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
    postbuildScripts:
      - name: Sign Nested ChatKit Frameworks
        shell: /bin/sh
        script: |
          FRAMEWORK_DIR="${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/FinClipChatKit.framework/Frameworks"
          if [ -d "${FRAMEWORK_DIR}" ]; then
            find "${FRAMEWORK_DIR}" -type d -name "*.framework" -print0 | while IFS= read -r -d '' FRAME; do
              /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --preserve-metadata=identifier,entitlements "${FRAME}" || exit 1
            done
          fi
    dependencies:
      - package: ChatKit

