name: SimpleObjC
options:
  bundleIdPrefix: com.finclip.chatkit
  deploymentTarget:
    iOS: "16.0"

schemes:
  SimpleObjC:
    build:
      targets:
        SimpleObjC: all
    run:
      config: Debug

packages:
  FinClipChatKit:
    url: https://github.com/Geeksfino/finclip-chatkit.git
    from: 0.7.2
  finclip-neuron:
    url: https://github.com/Geeksfino/finclip-neuron.git
    branch: main-swift6_0

targets:
  SimpleObjC:
    type: application
    platform: iOS
    sources:
      - path: App
        excludes:
          - "**/*.swift"
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.finclip.chatkit.simpleobjc
      PRODUCT_NAME: SimpleObjC
      INFOPLIST_KEY_CFBundleDisplayName: SimpleObjC
      INFOPLIST_FILE: App/Info.plist
      ENABLE_BITCODE: NO
    dependencies:
      - product: FinClipChatKit
        package: FinClipChatKit
      - product: NeuronKit
        package: finclip-neuron
      - product: SandboxSDK
        package: finclip-neuron
      - product: convstorelib
        package: finclip-neuron
      - product: ConvoUI
        package: finclip-neuron

