name: MyPal
options:
  bundleIdPrefix: com.finclip.chatkit
  deploymentTarget:
    iOS: "16.0"

schemes:
  MyPal:
    build:
      targets:
        MyPal: all
    run:
      config: Debug

packages:
  FinClipChatKit:
    url: https://github.com/Geeksfino/finclip-chatkit.git
    from: 0.7.4
  finclip-neuron:
    url: https://github.com/Geeksfino/finclip-neuron.git
    branch: main-swift6_0

targets:
  MyPal:
    type: application
    platform: iOS
    sources:
      - path: App/App
      - path: App/Extensions
      - path: App/ViewControllers
      - path: App/Network
      - path: App/Adapters
      - path: App/Models
        excludes:
          - "**/*.task"
          - "**/*.json"
          - "**/*.model"
          - "**/*.md"
          - "**/README.md"
    prebuildScripts:
      - name: Copy Model Files to Bundle
        shell: /bin/sh
        script: |
          MODEL_SRC="${SRCROOT}/App/Models"
          MODEL_DST="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/Models"
          if [ -d "${MODEL_SRC}" ]; then
            mkdir -p "${MODEL_DST}"
            [ -f "${MODEL_SRC}/gemma-3-270m-it-int8.task" ] && cp "${MODEL_SRC}/gemma-3-270m-it-int8.task" "${MODEL_DST}/" && echo "✅ Copied gemma-3-270m-it-int8.task"
          else
            echo "⚠️ Model source directory not found: ${MODEL_SRC}"
          fi
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.finclip.chatkit.mypal
      PRODUCT_NAME: MyPal
      INFOPLIST_KEY_CFBundleDisplayName: MyPal
      INFOPLIST_FILE: App/App/Info.plist
      CODE_SIGN_ENTITLEMENTS: App/App/MyPal.entitlements
      ENABLE_BITCODE: NO
    dependencies:
      - product: FinClipChatKit
        package: FinClipChatKit
      - product: NeuronKit
        package: finclip-neuron
      - product: SandboxSDK
        package: finclip-neuron
      - product: convstorelib
        package: finclip-neuron
      - product: ConvoUI
        package: finclip-neuron

