name: iLoveHK
options:
  bundleIdPrefix: com.finclip.chatkit
  deploymentTarget:
    iOS: "17.0"

packages:
  ChatKit:
    url: https://github.com/Geeksfino/finclip-chatkit.git
    from: 0.1.0

schemes:
  iLoveHK:
    build:
      targets:
        iLoveHK: all
    run:
      config: Debug

targets:
  iLoveHK:
    type: application
    platform: iOS
    sources:
      - path: App/App
      - path: App/Coordinators
      - path: App/Models
      - path: App/Network
      - path: App/ViewControllers
    resources:
      - path: App/Resources/Videos
        optional: true
      - path: App/Resources/Fixtures
        type: folder
    assetCatalogs:
      inputs:
        - App/Resources/Assets.xcassets
      appIcon: AppIcon
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      PRODUCT_BUNDLE_IDENTIFIER: com.finclip.chatkit.ilovehk
      PRODUCT_NAME: iLoveHK
      INFOPLIST_KEY_CFBundleDisplayName: iLoveHK
      INFOPLIST_FILE: App/App/Info.plist
      ENABLE_BITCODE: NO
      # Critical: Framework search paths for nested FinClipChatKit frameworks
      FRAMEWORK_SEARCH_PATHS[sdk=iphoneos*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      FRAMEWORK_SEARCH_PATHS[sdk=iphonesimulator*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      LD_RUNPATH_SEARCH_PATHS: $(inherited) @executable_path/Frameworks @loader_path/Frameworks @loader_path/Frameworks/FinClipChatKit.framework/Frameworks
      SWIFT_INCLUDE_PATHS[sdk=iphoneos*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
      SWIFT_INCLUDE_PATHS[sdk=iphonesimulator*]: $(inherited) $(BUILT_PRODUCTS_DIR)/FinClipChatKit.framework/Frameworks
    prebuildScripts:
      - name: Generate App Icons from AppLogo
        shell: /bin/sh
        script: |
          set -euo pipefail
          ICONSET_DIR="${PROJECT_DIR}/App/Resources/Assets.xcassets/AppIcon.appiconset"
          SRC_LOGO="${ICONSET_DIR}/AppLogo.png"
          if [ ! -f "${SRC_LOGO}" ]; then
            echo "❌ Source logo not found: ${SRC_LOGO}"
            exit 0
          fi
          command -v sips >/dev/null 2>&1 || { echo "❌ 'sips' not found"; exit 0; }
          TMP_DIR="${TEMP_DIR:-${DERIVED_DATA_DIR:-$(mktemp -d)}}/icons-gen"
          mkdir -p "${TMP_DIR}" "${ICONSET_DIR}"
          # size spec : output name -> max dimension
          generate_icon() {
            local filename="$1"; local size="$2"
            sips -s format png -Z "${size}" "${SRC_LOGO}" --out "${TMP_DIR}/${filename}" >/dev/null
            mv -f "${TMP_DIR}/${filename}" "${ICONSET_DIR}/${filename}"
          }
          generate_icon "AppIcon-20@2x.png" 40
          generate_icon "AppIcon-20@3x.png" 60
          generate_icon "AppIcon-29@2x.png" 58
          generate_icon "AppIcon-29@3x.png" 87
          generate_icon "AppIcon-40@2x.png" 80
          generate_icon "AppIcon-40@3x.png" 120
          generate_icon "AppIcon-60@2x.png" 120
          generate_icon "AppIcon-60@3x.png" 180
          generate_icon "AppIcon-20~ipad.png" 20
          generate_icon "AppIcon-20@2x~ipad.png" 40
          generate_icon "AppIcon-29~ipad.png" 29
          generate_icon "AppIcon-29@2x~ipad.png" 58
          generate_icon "AppIcon-40~ipad.png" 40
          generate_icon "AppIcon-40@2x~ipad.png" 80
          generate_icon "AppIcon-76~ipad.png" 76
          generate_icon "AppIcon-76@2x~ipad.png" 152
          generate_icon "AppIcon-83.5@2x~ipad.png" 167
          generate_icon "AppIcon-1024.png" 1024
          echo "✅ Generated app icons in ${ICONSET_DIR}"
      - name: Copy Splash Video
        shell: /bin/sh
        script: |
          SRC_FILE="${PROJECT_DIR}/App/Resources/Videos/splash.MP4"
          DEST_DIR="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/Videos"
          if [ -f "${SRC_FILE}" ]; then
            mkdir -p "${DEST_DIR}"
            cp -f "${SRC_FILE}" "${DEST_DIR}/splash.MP4"
            echo "📦 Copied splash.MP4 to ${DEST_DIR}"
          else
            echo "⚠️ splash.MP4 not found at ${SRC_FILE}"
          fi
      - name: Copy AppLogo PNG (runtime fallback)
        shell: /bin/sh
        script: |
          SRC_PNG="${PROJECT_DIR}/App/Resources/Assets.xcassets/AppLogo.imageset/AppLogo.png"
          DEST_DIR="${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}"
          if [ -f "${SRC_PNG}" ]; then
            mkdir -p "${DEST_DIR}"
            cp -f "${SRC_PNG}" "${DEST_DIR}/AppLogo.png"
            echo "📦 Copied AppLogo.png to ${DEST_DIR} (for UIImage named: AppLogo)"
          else
            echo "ℹ️ AppLogo.png not found at ${SRC_PNG} — relying on asset catalog if available"
          fi
    postbuildScripts:
      - name: Sign Nested ChatKit Frameworks
        shell: /bin/sh
        script: |
          FRAMEWORK_DIR="${TARGET_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/FinClipChatKit.framework/Frameworks"
          if [ -d "${FRAMEWORK_DIR}" ]; then
            find "${FRAMEWORK_DIR}" -type d -name "*.framework" -print0 | while IFS= read -r -d '' FRAME; do
              /usr/bin/codesign --force --sign "${EXPANDED_CODE_SIGN_IDENTITY}" --preserve-metadata=identifier,entitlements "${FRAME}" || exit 1
            done
          fi
    dependencies:
      - package: ChatKit